apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-03-27T15:04:10Z"
    labels:
      run: busybox
    name: busybox
    namespace: default
    resourceVersion: "684090"
    uid: 7bcc7060-2e57-4185-87e6-6f55d60bfe9c
  spec:
    containers:
    - command:
      - wget
      - 10.244.0.15:80/
      image: busybox
      imagePullPolicy: Always
      name: busybox
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-r96zq
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: minikube
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-r96zq
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T15:04:10Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T15:04:10Z"
      message: 'containers with unready status: [busybox]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T15:04:10Z"
      message: 'containers with unready status: [busybox]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T15:04:10Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://91820aaed5454ef495c012208be61bde913d7f8a35939cde01a6b32c2a096d7d
      image: busybox:latest
      imageID: docker-pullable://busybox@sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
      lastState:
        terminated:
          containerID: docker://da389d11334269e2a8073753afea9c18ead2eaa18e80a05e9c3f8fc9060f931b
          exitCode: 0
          finishedAt: "2023-03-27T15:04:13Z"
          reason: Completed
          startedAt: "2023-03-27T15:04:13Z"
      name: busybox
      ready: false
      restartCount: 2
      started: false
      state:
        terminated:
          containerID: docker://91820aaed5454ef495c012208be61bde913d7f8a35939cde01a6b32c2a096d7d
          exitCode: 0
          finishedAt: "2023-03-27T15:04:31Z"
          reason: Completed
          startedAt: "2023-03-27T15:04:31Z"
    hostIP: 192.168.49.2
    phase: Running
    podIP: 10.244.0.17
    podIPs:
    - ip: 10.244.0.17
    qosClass: BestEffort
    startTime: "2023-03-27T15:04:10Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-03-27T14:48:03Z"
    labels:
      run: nginx
    name: nginx
    namespace: default
    resourceVersion: "683322"
    uid: 4fdebc8b-a263-4db8-8ddc-76a2bcc17c47
  spec:
    containers:
    - image: nginx:1.7.1
      imagePullPolicy: Always
      name: nginx
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-49mr9
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: minikube
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-49mr9
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T14:48:03Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T14:48:05Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T14:48:05Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-03-27T14:48:03Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://2b56aaf516ff8d1f37af0cb4d9442bed1c0630ff5c529f79009c3d59b4f955e0
      image: nginx:1.7.1
      imageID: docker-pullable://nginx@sha256:7fbe0579e123f3d2b29c9159e9a80547fb72621bb419e52d98c679ddbf1055a1
      lastState:
        terminated:
          containerID: docker://15ebfa7cd0d38fe1e39aebafccfa633d0e7859aa33c031cea253ae27b29aa972
          exitCode: 0
          finishedAt: "2023-03-27T14:49:42Z"
          reason: Completed
          startedAt: "2023-03-27T14:48:04Z"
      name: nginx
      ready: true
      restartCount: 1
      started: true
      state:
        running:
          startedAt: "2023-03-27T14:49:52Z"
    hostIP: 192.168.49.2
    phase: Running
    podIP: 10.244.0.15
    podIPs:
    - ip: 10.244.0.15
    qosClass: BestEffort
    startTime: "2023-03-27T14:48:03Z"
kind: List
metadata:
  resourceVersion: ""
