apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busybox-echo
spec:
  startingDeadlineSeconds: 17
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox-echo
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: busybox-echo
            resources: {}
            command: ["/bin/sh","-c","date; echo Hello from the Kubernetes cluster"]
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
