apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: job30secs5
spec:
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        command: ["/bin/sh", "-c","echo hello; sleep 30;echo world"]
        name: nginx
        resources: {}
      restartPolicy: Never
status: {}
