apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipodnginxbusybox
  name: multipodnginxbusybox
spec:
  containers:
  - image: nginx
    name: multipodnginxbusybox
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: "/usr/share/nginx/html" 
      name: empty
  initContainers:
  - image: busybox
    name: busybox
    command: 
    - /bin/sh
    - -c
    - "wget -O /work-dir/index.html http://neverssl.com/online"
    volumeMounts:
    - mountPath: "/work-dir"
      name: empty
  volumes:
  - name: empty
    emptyDir: 
      sizeLimit: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
