apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - /bin/sh
    - '-c'
    - 'echo hello; sleep 3600'
    image: busybox
    name: busybox
    resources: {}
  - command:
    - /bin/sh
    - '-c'
    - 'echo hello; sleep 3600'
    image: busybox
    name: busybox2
    resources: {}
  dnsPolicy: ClusterFirst
status: {}
