apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxsecretasenv
  name: nginxsecretasenv
spec:
  containers:
  - image: nginx
    name: nginxsecretasenv
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
