apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxcm
  name: nginxcm
spec:
  containers:
  - image: nginx
    name: nginxcm
    env:
      - name: option
        valueFrom:
          configMapKeyRef:
            name: options
            key: var5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
