apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxsecretasvolume
  name: nginxsecretasvolume
spec:
  containers:
  - image: nginx
    name: nginxsecretasvolume
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: /etc/foo
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
