apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxcmanotherone
  name: nginxcmanotherone
spec:
  containers:
  - image: nginx
    name: nginxcmanotherone
    envFrom:
      - configMapRef:
          name: anotherone
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
