apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxcmasvolume
  name: nginxcmasvolume
spec:
  containers:
  - image: nginx
    name: nginxcmasvolume
    volumeMounts:
      - name: cm-volume
        mountPath: /etc/lala
  volumes:
  - name: cm-volume
    configMap:
      name: cmvolume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
