apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxtolerate
  name: nginxtolerate
spec:
  containers:
  - image: nginx
    name: nginxtolerate
    resources: {}
  tolerations:
  - key: tier
    operator: Equal
    value: frontend
    effect: NoSchedule
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
