apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxtolerate
  name: nginxtolerate
spec:
  containers:
  - image: nginx
    name: nginxtolerate
    resources: {}
  nodeSelector:
    kubernetes.io.hostname: controlplane
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: Exists
    effect: NoSchedule
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
